# Generated by Django 4.1.7 on 2023-03-28 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.CharField(max_length=12)),
                ('address', models.TextField()),
                ('position', models.CharField(choices=[('developer', 'developer'), ('tester', 'tester'), ('manager', 'manager')], max_length=100)),
                ('company', models.CharField(max_length=100)),
            ],
        ),
    ]
